/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      backgroundColor: {
        color1: "var(--color1)",
        color2: "var(--color2)",
        coloredBg: "var(--coloredBg)",
        editButton: "var(--editButton)",
        addButton: "var(--addButton)",
        deleteButton: "var(--deleteButton)",
        sidebarBg1: "var(--sidebarBg1)",
        sidebarBg2: "var(--sidebarBg2)",
        border1: "var(--border1)",
        hoverLink: "var(--hoverLink)",
        sidebarText: "var(--sidebarText)",
        sidebarBgHover: "var(--sidebarBgHover)",
        sidebarBgActive: "var(--sidebarBgActive)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        color1: "var(--color1)",
        color2: "var(--color2)",
        coloredBg: "var(--coloredBg)",
        editButton: "var(--editButton)",
        addButton: "var(--addButton)",
        deleteButton: "var(--deleteButton)",
        sidebarBg1: "var(--sidebarBg1)",
        sidebarBg2: "var(--sidebarBg2)",
        border1: "var(--border1)",
        hoverLink: "var(--hoverLink)",
        sidebarText: "var(--sidebarText)",
        sidebarBgHover: "var(--sidebarBgHover)",
        sidebarBgActive: "var(--sidebarBgActive)",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "var(--deleteButton)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
